src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $auteur = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $heure = null;

    #[ORM\Column(length: 255)]
    private ?string $img_produit = null;

    #[ORM\Column(nullable: true)]
    private ?int $nb_achat = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'produit', orphanRemoval: true)]
    private Collection $comment;

    #[ORM\ManyToMany(targetEntity: Panier::class, mappedBy: 'produits')]
    private Collection $paniers;

    public function __construct()
    {
        $this->comment = new ArrayCollection();
        $this->paniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): static
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getHeure(): ?\DateTimeInterface
    {
        return $this->heure;
    }

    public function setHeure(?\DateTimeInterface $heure): static
    {
        $this->heure = $heure;

        return $this;
    }

    public function getImgProduit(): ?string
    {
        return $this->img_produit;
    }

    public function setImgProduit(string $img_produit): static
    {
        $this->img_produit = $img_produit;

        return $this;
    }

    public function getNbAchat(): ?int
    {
        return $this->nb_achat;
    }

    public function setNbAchat(?int $nb_achat): static
    {
        $this->nb_achat = $nb_achat;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comment->contains($comment)) {
            $this->comment->add($comment);
            $comment->setProduit($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getProduit() === $this) {
                $comment->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): static
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers->add($panier);
            $panier->addProduit($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): static
    {
        if ($this->paniers->removeElement($panier)) {
            $panier->removeProduit($this);
        }

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\User;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use App\Entity\Category;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('auteur')
            ->add('description')
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'titre',
            ])
            ->add('date', DateType::class)
            ->add('heure', TimeType::class)
            ->add('image', FileType::class, [
                'label' => 'Image (fichier PNG ou JPG)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '200k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Sélectionnez un fichier JPEG ou PNG de poids inférieur à 200Ko',
                    ])
                ],
            ])
            // ->add('nb_achat')
            ->add('prix')
            // ->add('user', EntityType::class, [
            //     'class' => User::class,
            //     'choice_label' => 'id',
            // ])
            // ->add('category', EntityType::class, [
            //     'class' => Category::class,
            //     'choice_label' => 'id',
            // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Form\ProduitFilterType;
use Symfony\Component\HttpFoundation\RedirectResponse;


#[Route('/produit')]
class ProduitController extends AbstractController
{

    #[Route('/', name: 'app_produit_index', methods: ['GET', 'POST'])]
    public function index(Request $request, ProduitRepository $produitRepository): Response
    {
        $produits = $produitRepository->findAll();
        return $this->render('produit/index.html.twig', [
            'produits' => $produits,
        ]);
    }


    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger, ProduitRepository $produitRepository): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser(); // récupère l'utilisateur actuellement connecté
            if (!$user) {
                throw new \Exception('Vous devez être connecté pour créer un produit');
            }

            $produit->setUser($user); // associe l'utilisateur au produit

            // Augmenter le nb_produit de la catégorie
            $category = $produit->getCategory();
            $nbProduits = $produitRepository->count(['category' => $category]) + 1;
            $category->setNbProduit($nbProduits);

            /** @var UploadedFile $imageFile */
            $imageFile = $form['image']->getData();

            // cette condition est nécessaire car le champ 'image' n'est pas obligatoire
            // ducoup, le fichier doit être traité que lorsqu'un fichier est téléchargé
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // pour inclure en toute sécurité le nom de fichier comme partie de l'URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                // deplace le fichier dans le dossier où sont stockées les images
                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // au caou
                    throw new \Exception('Une erreur est survenue lors du téléchargement du fichier');
                }
                $produit->setImgProduit($newFilename);
            }

            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $user = $this->getUser(); // récupère l'utilisateur actuellement connecté
        if (!$user || $user->getId() !== $produit->getUser()->getId()) {
            throw $this->createAccessDeniedException('Vous ne pouvez pas éditer ce produit');
        }

        $oldImage = $produit->getImgProduit();

        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form['image']->getData();

            // Si une nouvelle image a été téléchargée
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                // deplace le fichier dans le dossier où sont stockées les images
                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw new \Exception('Une erreur est survenue lors du téléchargement du fichier');
                }

                // Supprime l'ancienne image
                $oldImagePath = $this->getParameter('images_directory') . '/' . $oldImage;
                if (file_exists($oldImagePath)) {
                    unlink($oldImagePath);
                }

                $produit->setImgProduit($newFilename);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager, ProduitRepository $produitRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $produit->getId(), $request->request->get('_token'))) {
            // Supprime le fichier associé à l'entité
            $imagePath = $this->getParameter('images_directory') . '/' . $produit->getImgProduit();
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }

            $category = $produit->getCategory();
            $nbProduits = $produitRepository->count(['category' => $category]) - 1;
            $category->setNbProduit($nbProduits);

            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }

    // #[Route('/admin', name: 'admin_users')]
    // public function listProduits(ProduitRepository $produitRepository): Response
    // {
    //     $produits = $produitRepository->findAll();

    //     return $this->render('admin/index.html.twig', [
    //         'produits' => $produits,
    //     ]);
    // }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}

<p>ID de l'utilisateur connecté : {{ app.user.id }}</p>
<button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/filter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Filtrer les produits{% endblock %}

{% block body %}
<h1>Filtrer les produits</h1>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>titre</th>
            <th>Prix</th>
            <th>Date</th>
            <th>Auteur</th>
        </tr>
    </thead>
    <tbody>
        {% for produit in produits %}
        <tr>
            <td>{{ produit.id }}</td>
            <td>{{ produit.titre }}</td>
            <td>{{ produit.prix }}</td>
            <td>{{ produit.date|date('Y-m-d') }}</td>
            <td>{{ produit.auteur }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
<h1>Produit index</h1>


{% if form is defined %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endif %}


<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Description</th>
            <th>Category</th>
            <th>Date</th>
            <th>Heure</th>
            <th>Img_produit</th>
            <th>Nb_achat</th>
            <th>Prix</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        {% for produit in produits %}
        <tr>
            <td>{{ produit.id }}</td>
            <td>{{ produit.titre }}</td>
            <td>{{ produit.auteur }}</td>
            <td>{{ produit.description }}</td>
            <td>{{ produit.category.titre }}</td>
            <td>{{ produit.date ? produit.date|date('Y-m-d') : '' }}</td>
            <td>{{ produit.heure ? produit.heure|date('H:i') : '' }}</td>
            <td>{{ produit.imgProduit }}</td>
            <td>{{ produit.nbAchat }}</td>
            <td>{{ produit.prix }}</td>
            <td>
                <a href="{{ path('app_produit_show', {'id': produit.id}) }}">show</a>
                {% if app.user and app.user.id == produit.user.id %}
                <a href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>
                {% endif %}
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="10">no records found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{{ path('app_produit_new') }}">Create new</a>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('app_produit_index') }}">back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
<h1>Produit</h1>

<table class="table">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ produit.id }}</td>
        </tr>
        <tr>
            <th>Titre</th>
            <td>{{ produit.titre }}</td>
        </tr>
        <tr>
            <th>Auteur</th>
            <td>{{ produit.auteur }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ produit.description }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ produit.date ? produit.date|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Heure</th>
            <td>{{ produit.heure ? produit.heure|date('H:i') : '' }}</td>
        </tr>
        <tr>
            <th>Img_produit</th>
            <td><img src="{{ asset('uploads/images/' ~ produit.ImgProduit) }}" alt=""></td>
        </tr>
        <tr>
            <th>Nb_achat</th>
            <td>{{ produit.nbAchat }}</td>
        </tr>
        <tr>
            <th>Prix</th>
            <td>{{ produit.prix }}</td>
        </tr>
    </tbody>
</table>

<a href="{{ path('app_panier_add', {'id': produit.id}) }}" class="btn btn-primary">Ajouter au panier</a>

<a href="{{ path('app_produit_index') }}">Retour à la liste</a>

{% if app.user and app.user.id == produit.user.id %}
<a href="{{ path('app_produit_edit', {'id': produit.id}) }}">Modifier</a>
{% endif %}

{# {% include('produit/_delete_form.html.twig') %} #}


{% endblock %}